### PR TITLE
Update the ItemValidation interface to apply to Media class

### LINKED ISSUE #31: Move the itemValidation Interface from the Book Class to the Media Class
**Description:**

Before extending the system to incorporate multiple media types, we only implement the interface to the Book class. This interface should be implemented to the Media class instead.

**Code Snippet:**

Screenshot 2024-09-29 at 4 50 58 PM

**Problem:**

itemValidation interface should be implemented to all the Media types.

**Suggested Solution:**

Remove the interface implementation on the Book class. 
Add the interface implementation to the Media class.

### PR DESCRIPTION
**Pull request by AgLyx3**
**Description:**

As a result of expanding the system to cover multiple media forms, we need to implement the validation interface that was originally implemented in the Book class to the Media class.

**Changes made:**

Add 4 default methods in the ItemValidation class.
Add 4 abstract getters that have been overridden in the Media class in the ItemValidation class to get the fields we need for validation.
Implement the interface to the Media class.

**Additional Notes:**

We may want to add additional customized validation methods in the DVDs & audiobooks & E-Book class in the future.

### CODE REVIEW

**Comment by cathymonkey** [comment]
Nice implementation of the `ItemValidation` interface!

Have you checked if your `Book.java` is the latest version? It seems outdated compared to the main branch, because `Book` is not initializing using `super()` from its parent class `Media`.

**Comment by cathymonkey** [comment]
Also, if we want to add additional customized validation methods in the DVDs & audiobooks & E-Book class in the future, we might want to consider converting this interface to an abstract class so that it can support shared common validation behavior across classes while containing abstract methods for unique validation methods specific to each class. 

Some ideas for unique validation:

`DVDs`: `isLengthValid`, `isSubstitlesValid`

`Audiobooks`: `isNarratorValid`

`Ebooks`: `isPDFValid`

**Comment by cathymonkey** [comment]
Or, actually, we can keep the interface and have unique validation methods implemented in each class? What do you think?

**Comment by AgLyx3** [comment]
> Also, if we want to add additional customized validation methods in the DVDs & audiobooks & E-Book class in the future, we might want to consider converting this interface to an abstract class so that it can support shared common validation behavior across classes while containing abstract methods for unique validation methods specific to each class.
> 
> Some ideas for unique validation:
> 
> `DVDs`: `isLengthValid`, `isSubstitlesValid`
> 
> `Audiobooks`: `isNarratorValid`
> 
> `Ebooks`: `isPDFValid`

I love your proposal for the validation method that could be implemented for individual media types. In terms of converting it to an abstract class, do you mean that we may want some subinterfaces for each type of media?

**Comment by AgLyx3** [comment]
> Or, actually, we can keep the interface and have unique validation methods implemented in each class? What do you think?

Just to add to my previous comment, I think we could also try to have an ItemValidation interface for shared methods and have subinterfaces like BookValidation, DVDsValidation, etc., for the unique methods you suggested.

**Comment by cathymonkey** [comment]
Yeah, I like the idea of having subinterfaces. Just to clarify, would it be something as follows:

```.java
public interface ItemValidation{}

public interface BookValidation extends ItemValidation{}

public interface DVDsValidation extends ItemValidation{}
```
etc. ?

**Comment by AgLyx3** [comment]
> Yeah, I like the idea of having subinterfaces. Just to clarify, would it be something as follows:
> 
> ```java
> public interface ItemValidation{}
> 
> public interface BookValidation extends ItemValidation{}
> 
> public interface DVDsValidation extends ItemValidation{}
> ```
> 
> etc. ?

Yes, that is exactly what I was thinking!

**Comment by AgLyx3** [comment]
> Nice implementation of the `ItemValidation` interface!
> 
> Have you checked if your `Book.java` is the latest version? It seems outdated compared to the main branch, because `Book` is not initializing using `super()` from its parent class `Media`.

Thank you for your review! I think the version works fine since I didn't make changes to those lines.

**Comment by cathymonkey** [comment]
I have a small suggestion. Would `MediaValidation` sound more coherent than `ItemValidation` in this project?

**Comment by AgLyx3** [comment]
> I have a small suggestion. Would `MediaValidation` sound more coherent than `ItemValidation` in this project?

Nice catch! I do think `MediaValidation` makes more sense here. I'll change the name right now accordingly. For the idea of the subinterfaces, I think I need to create a new issue after all new features have been implemented.

**Comment by cathymonkey** [comment]
OK, see you in the next issue! Awesome work!
Merged.

**Pull request merged**
